### PR TITLE
Drop AJV and Zod support in favor of TypeBox

### LINKED ISSUE #675: response typings cause TypeScript errors
**Describe the bug**

image

**To Reproduce**:

https://github.com/ardatan/feTS/pull/674

**Expected behavior**

**Environment:**

- OS:
- `package-name...`:
- NodeJS:

**Additional context**

### PR DESCRIPTION
**Pull request by ardatan**
Closes #674
Closes #675
Closes https://github.com/ardatan/feTS/issues/202

### CODE REVIEW

File: packages/fets/src/plugins/typebox.ts [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+import { Value } from '@sinclair/typebox/value';
+import { Response } from '../Response.js';
+import { PromiseOrValue, RouterComponentsBase, RouterPlugin, RouterRequest } from '../types.js';
+import { getHeadersObj } from './utils.js';
+
+type ValidateRequestFn = (request: RouterRequest) => PromiseOrValue<ValueErrorIterator | []>;
+
+function createValidateFn(schema: any) {
+  try {
+    const validator = TypeCompiler.Compile(schema);
```
Comment (n1ru4l) [inline packages/fets/src/plugins/typebox.ts:11]: This should be cached, we don't want to compile the models from scratch for each request.

File: packages/fets/src/plugins/typebox.ts [hunk 2]
```diff
@@ -0,0 +1,147 @@
...
+    };
+  } catch (e) {
+    return function getErrors(data: any) {
+      return Value.Errors(schema, data);
+    };
+  }
+}
+
+export function useTypeBox({
+  components = {},
```
Comment (n1ru4l) [inline packages/fets/src/plugins/typebox.ts:23]: What is this? Do we need it?

File: packages/fets/src/plugins/typebox.ts (hunk 1 above)
Comment (ardatan) [reply packages/fets/src/plugins/typebox.ts:11]: It is created once and used later in the returned function below

**Review by dotansimha — APPROVED** [review]
